services:
  db:
    image: postgres:16-alpine
    container_name: reloop-db
    environment:
      POSTGRES_DB: ewaste
      POSTGRES_USER: ewaste
      POSTGRES_PASSWORD: ewaste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
